ignoredOptionalDependencies:
  - better-sqlite3

shamefullyHoist: true
shellEmulator: true

allowBuilds:
  '@parcel/watcher': false
  '@tailwindcss/oxide': false
  esbuild: false
  sharp: false
  unrs-resolver: false
  vue-demi: false
  workerd: true
