shamefullyHoist: true

shellEmulator: true
ignoredOptionalDependencies:
  - better-sqlite3

allowBuilds:
  '@parcel/watcher': false
  '@tailwindcss/oxide': false
  esbuild: false
  sharp: false
  unrs-resolver: false
  vue-demi: false
  workerd: true
